import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Add_Student.java
 *
 * Created on Nov 9, 2016, 2:51:40 PM
 */

/**
 *
 * @author admin
 */
public class Add_Student extends javax.swing.JFrame {

    /** Creates new form Add_Student */
    public Add_Student() {
        initComponents();
        setSize(800,600);
        setLocation(500,300);
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRno = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        txtSec = new javax.swing.JTextField();
        txtscience = new javax.swing.JTextField();
        txtsst = new javax.swing.JTextField();
        txtMM = new javax.swing.JTextField();
        txtTM = new javax.swing.JTextField();
        txtPer = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        btnCal = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        PS = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txteng = new javax.swing.JTextField();
        txthin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ROLL NO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 122, 50, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 157, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CLASS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 192, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SECTION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("SCIENCE MARKS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 122, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("SOCIAL SCIENCE MARKS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 157, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("TOTAL MARKS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 308, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("PERCENTAGE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 268, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("GRADE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 308, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PREFFERED STREAM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 377, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("MATHS MARKS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 192, -1, -1));
        getContentPane().add(txtRno, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 119, 99, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 150, 99, -1));
        getContentPane().add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 189, 99, -1));
        getContentPane().add(txtSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 227, 99, -1));
        getContentPane().add(txtscience, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 119, 95, -1));
        getContentPane().add(txtsst, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 157, 96, -1));
        getContentPane().add(txtMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 189, 96, -1));

        txtTM.setEditable(false);
        getContentPane().add(txtTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 303, 96, -1));

        txtPer.setEditable(false);
        getContentPane().add(txtPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 265, 99, -1));

        txtGrade.setEditable(false);
        txtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 303, 99, -1));

        btnCal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCal.setText("CALCULATE");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        getContentPane().add(btnCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 424, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 424, -1, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 424, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 424, -1, -1));

        PS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PCM", "PCB", "COMMERCE" }));
        getContentPane().add(PS, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 374, 108, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setText("STUDENT DETAILS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("ENGLISH MARKS ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 230, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("HINDI MARKS");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 268, -1, -1));
        getContentPane().add(txteng, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 227, 96, -1));

        txthin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthinActionPerformed(evt);
            }
        });
        getContentPane().add(txthin, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 265, 96, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtNameActionPerformed

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtGradeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String RNo = txtRno.getText();
        String Nam = txtName.getText();
        int Cl = Integer.parseInt(txtClass.getText());
        String Sec = txtSec.getText();
        int SM = Integer.parseInt(txtscience.getText());
        int SST = Integer.parseInt(txtsst.getText());
        int MM = Integer.parseInt(txtMM.getText());
        int EM = Integer.parseInt(txteng.getText());
        int HM = Integer.parseInt(txthin.getText());
        int Total = Integer.parseInt(txtTM.getText());
        int Per = Integer.parseInt(txtPer.getText());
        String Gr = txtGrade.getText();
        String PSt = (String)PS.getSelectedItem();
         try
         {
             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = (Connection)
                     DriverManager.getConnection("jdbc:mysql://localhost:3306/Stream","root","12345");
             Statement stmt = con.createStatement();
             String str = "Insert into Student Values('"+RNo+"','"+Nam+"',"+Cl+",'"+Sec+"',"+SM+","+SST+","+MM+","+EM+","+HM+","+Total+","+Per+",'"+Gr+"','"+PSt+"', NULL"+")";
             stmt.executeUpdate(str);
             JOptionPane.showMessageDialog(this,"RECORD ADDED");


             
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(this,e.getMessage());
         }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        int sm = Integer.parseInt(txtscience.getText());
        int cm = Integer.parseInt(txtsst.getText());
        int mm = Integer.parseInt(txtMM.getText());
        int em= Integer.parseInt(txteng.getText());
        int hin = Integer.parseInt(txthin.getText());
        int TotalMarks = sm +cm+mm+em+hin;
        txtTM.setText("" + TotalMarks);
        int Percentage = TotalMarks/5;
        txtPer.setText("" + Percentage);
        if (Percentage>=90)
            txtGrade.setText("A");
        else if(Percentage>=80)
           txtGrade.setText("B");
        else if (Percentage>=70)
            txtGrade.setText("C");
        else
            txtGrade.setText("D");


    }//GEN-LAST:event_btnCalActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtRno.setText("");
        txtName.setText("");
        txtClass.setText("");
        txtSec.setText("");
        txtscience.setText("");
        txtsst.setText("");
        txtMM.setText("");
        txtTM.setText("");
        txthin.setText("");
        txteng.setText("");
        
        txtPer.setText("");
        txtGrade.setText("");
       
         
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
                    new Menu().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txthinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthinActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox PS;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtMM;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPer;
    private javax.swing.JTextField txtRno;
    private javax.swing.JTextField txtSec;
    private javax.swing.JTextField txtTM;
    private javax.swing.JTextField txteng;
    private javax.swing.JTextField txthin;
    private javax.swing.JTextField txtscience;
    private javax.swing.JTextField txtsst;
    // End of variables declaration//GEN-END:variables

}
