import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * delstudent.java
 *
 * Created on Nov 28, 2016, 1:11:46 PM
 */

/**
 *
 * @author Administrator
 */
public class delstudent extends javax.swing.JFrame {

    /** Creates new form delstudent */
    public delstudent() {
        initComponents();
        setSize(800,600);
        setLocation(500,300);
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCl = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSec = new javax.swing.JTextField();
        txtPS = new javax.swing.JTextField();
        txtPer = new javax.swing.JTextField();
        txtRno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtscience = new javax.swing.JTextField();
        txtsst = new javax.swing.JTextField();
        txtMM = new javax.swing.JTextField();
        txtTM = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txteng = new javax.swing.JTextField();
        txthin = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setText("ADD ROLL NO");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, -1, -1));

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, 99, 250));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PREFFERED STREAM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 328, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ROLL NO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 50, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SECTION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 226, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CLASS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));
        getContentPane().add(txtCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 185, 99, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 153, 99, -1));
        getContentPane().add(txtSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 223, 99, -1));

        txtPS.setEditable(false);
        getContentPane().add(txtPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 325, 99, -1));

        txtPer.setEditable(false);
        txtPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerActionPerformed(evt);
            }
        });
        getContentPane().add(txtPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 261, 99, -1));
        getContentPane().add(txtRno, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 115, 99, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("PERCENTAGE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 261, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("SST MARKS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 156, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("SCIENCE MARKS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 118, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("MATHS MARKS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 188, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("TOTAL MARKS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 341, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("GRADE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 302, -1, -1));
        getContentPane().add(txtscience, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 115, 90, -1));
        getContentPane().add(txtsst, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 153, 90, -1));
        getContentPane().add(txtMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 185, 90, -1));

        txtTM.setEditable(false);
        txtTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTMActionPerformed(evt);
            }
        });
        getContentPane().add(txtTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 340, 90, -1));

        txtGrade.setEditable(false);
        txtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 299, 90, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("ENGLISH MARKS ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 221, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("HINDI MARKS");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 264, -1, -1));

        txteng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtengActionPerformed(evt);
            }
        });
        getContentPane().add(txteng, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 218, 90, -1));
        getContentPane().add(txthin, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 261, 90, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setText("DELETE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 451, -1, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 451, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 451, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setText("DELETE FORM");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        DefaultListModel dm = (DefaultListModel)jList1.getModel();
        String str = "Select Roll_No From Student";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Stream","root","12345");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(str);
            while(rs.next()) {
                String rn = rs.getString("Roll_No");
                dm.addElement(rn);

            }
            con.close();


        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_btnAddActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        String rn = (String)jList1.getSelectedValue();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Stream","root","12345");
            Statement stmt = con.createStatement();
            String str = "Select* From Student Where Roll_No = '"+rn+"'";
            ResultSet rs = stmt.executeQuery(str);
            if(rs.next()) {
                String rno = rs.getString("Roll_No");
                String nm = rs.getString("Name");
                int cl = rs.getInt("Class");
                String sec = rs.getString("Section");
                int sm = rs.getInt("Science");
                int sstm = rs.getInt("SST");
                int mm = rs.getInt("Maths");
                int eng = rs.getInt("English");
                int hin = rs.getInt("Hindi");
                int tm = rs.getInt("Total");
                int per = rs.getInt("Percentage");
                String gr = rs.getString("Grade");
                String pf = rs.getString("PrefStream");
                txtRno.setText(""+ rno);
                txtName.setText(""+ nm);
                txtCl.setText(""+ cl);
                txtSec.setText(""+ sec);
                txtscience.setText(""+ sm);
                txtsst.setText(""+ sstm);
                txtMM.setText(""+ mm);
                txteng.setText(""+ eng);
                txthin.setText(""+ hin);
                txtTM.setText(""+ tm);
                txtPer.setText(""+ per);
                txtGrade.setText(""+ gr);
                txtPS.setText(""+ pf);





            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_jList1MouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtNameActionPerformed

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtGradeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String rno = txtRno.getText();
        String nm = txtName.getText();
        int cl = Integer.parseInt(txtCl.getText());
        String sec = txtSec.getText();
        int sm = Integer.parseInt(txtscience.getText());
        int sstm = Integer.parseInt(txtsst.getText());
        int mm = Integer.parseInt(txtMM.getText());
        int em = Integer.parseInt(txteng.getText());
        int hm = Integer.parseInt(txthin.getText());
        int tm = Integer.parseInt(txtTM.getText());
        int per = Integer.parseInt(txtPer.getText());
        String gr = txtGrade.getText();
        String ps = txtPS.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/Stream","root","12345");
            Statement stmt = con.createStatement();
            String str = "Delete From Student  Where Roll_No = '"+(rno)+"'";
            int r = stmt.executeUpdate(str);
            JOptionPane.showMessageDialog(this,"RECORD DELETED");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtRno.setText("");
        txtName.setText("");
        txtCl.setText("");
        txtSec.setText("");
        txtscience.setText("");
        txtsst.setText("");
        txteng.setText("");
        txthin.setText("");
        txtMM.setText("");
        txtTM.setText("");
        txtPer.setText("");
        txtGrade.setText("");
        txtPS.setText("");
}//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu().setVisible(true);
}//GEN-LAST:event_btnBackActionPerformed

    private void txtengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtengActionPerformed

    private void txtTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTMActionPerformed

    private void txtPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCl;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtMM;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPS;
    private javax.swing.JTextField txtPer;
    private javax.swing.JTextField txtRno;
    private javax.swing.JTextField txtSec;
    private javax.swing.JTextField txtTM;
    private javax.swing.JTextField txteng;
    private javax.swing.JTextField txthin;
    private javax.swing.JTextField txtscience;
    private javax.swing.JTextField txtsst;
    // End of variables declaration//GEN-END:variables

}
