import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Part_Stud.java
 *
 * Created on Nov 22, 2016, 1:54:33 PM
 */

/**
 *
 * @author Administrator
 */
public class Part_Stud extends javax.swing.JFrame {

    /** Creates new form Part_Stud */
    public Part_Stud() {
        initComponents();
        setSize(800,600);
        setLocation(500,300);
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CM = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        txtSec = new javax.swing.JTextField();
        txtRno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        txtTM = new javax.swing.JTextField();
        txtsst = new javax.swing.JTextField();
        txtsc = new javax.swing.JTextField();
        txtMM = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPS = new javax.swing.JTextField();
        txtAS = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txteng = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txthin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("SELECT ROLL NO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(138, 80, 90, 14);

        CM.setModel(new DefaultComboBoxModel());
        CM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMMouseClicked(evt);
            }
        });
        CM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMActionPerformed(evt);
            }
        });
        getContentPane().add(CM);
        CM.setBounds(272, 77, 82, 22);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ROLL NO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 84, -1, -1));

        jLabel4.setText("SECTION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 199, -1, -1));

        jLabel3.setText("CLASS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 162, -1, -1));

        jLabel5.setText("NAME");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 118, -1, -1));

        txtName.setEditable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 120, 136, -1));

        txtClass.setEditable(false);
        txtClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassActionPerformed(evt);
            }
        });
        jPanel1.add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 159, 136, -1));

        txtSec.setEditable(false);
        txtSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecActionPerformed(evt);
            }
        });
        jPanel1.add(txtSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 199, 136, -1));

        txtRno.setEditable(false);
        jPanel1.add(txtRno, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 85, 136, -1));

        jLabel8.setText("PERCENTAGE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 249, -1, -1));

        txtPer.setEditable(false);
        txtPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerActionPerformed(evt);
            }
        });
        jPanel1.add(txtPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 246, 136, -1));

        jLabel6.setText("SST MARKS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 181, -1, -1));

        jLabel7.setText("SCIENCE MARKS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 88, -1, -1));

        jLabel9.setText("TOTAL MARKS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 246, -1, -1));

        jLabel11.setText("MATHS MARKS");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 214, -1, -1));

        jLabel10.setText("GRADE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 287, -1, -1));

        txtGrade.setEditable(false);
        txtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });
        jPanel1.add(txtGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 284, 90, -1));

        txtTM.setEditable(false);
        txtTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTMActionPerformed(evt);
            }
        });
        jPanel1.add(txtTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 243, 90, -1));

        txtsst.setEditable(false);
        txtsst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsstActionPerformed(evt);
            }
        });
        jPanel1.add(txtsst, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 178, 90, -1));

        txtsc.setEditable(false);
        jPanel1.add(txtsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 85, 90, -1));

        txtMM.setEditable(false);
        jPanel1.add(txtMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 208, 90, -1));

        jLabel12.setText("PREFFERED STREAM");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 304, -1, -1));

        txtPS.setEditable(false);
        jPanel1.add(txtPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 301, 135, -1));

        txtAS.setEditable(false);
        jPanel1.add(txtAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 324, 90, -1));

        jLabel13.setText("ALLOCATED STREAM");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 327, -1, -1));

        jLabel15.setText("ENGLISH MARKS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 123, -1, -1));

        txteng.setEditable(false);
        jPanel1.add(txteng, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 120, 90, -1));

        jLabel16.setText("HINDI MARKS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 152, -1, -1));

        txthin.setEditable(false);
        jPanel1.add(txthin, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 149, 90, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, 110, 830, 390);

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setText("DETAILS OF PARTICULAR STUDENT");
        jLabel14.setAutoscrolls(true);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(231, 11, 450, 34);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(613, 76, 70, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtNameActionPerformed

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtGradeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         jPanel1.setVisible(false);
         //jPanel2.setVisible(true);
         DefaultComboBoxModel cm = (DefaultComboBoxModel)CM.getModel();
         String str = "Select Roll_No From Student";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/Stream","root","12345");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(str);
            while(rs.next())
            {
             String rn = rs.getString("Roll_No");
             cm.addElement(rn);

            }
            con.close();


        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void CMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMMouseClicked
         jPanel1.setVisible(true);
        // TODO add your handling code here:

        String rn = (String)CM.getSelectedItem();
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Stream","root","12345");
            Statement stmt = con.createStatement();
            String str = "Select* From Student Where Roll_No = '"+rn+"'";
            ResultSet rs = stmt.executeQuery(str);
            if(rs.next())
            {
                String rno = rs.getString("Roll_No");
                String nm = rs.getString("Name");
                int cl = rs.getInt("Class");
                String sec = rs.getString("Section");
                int sm = rs.getInt("Science");
                int sstm = rs.getInt("SST");
                int mm = rs.getInt("Maths");
                int em = rs.getInt("English");
                int hm = rs.getInt("Hindi");
                int tm = rs.getInt("Total");

                int per = rs.getInt("Percentage");
                String gr = rs.getString("Grade");
                String pf = rs.getString("PrefStream");
                String as = rs.getString("AlloStream");
                txtRno.setText(""+ rno);
                txtName.setText(""+ nm);
                txtClass.setText(""+ cl);
                txtSec.setText(""+ sec);
                txtsc.setText(""+sm);
                txtsst.setText(""+sstm);
                txtMM.setText(""+ mm);
                txteng.setText(""+ em);
                txthin.setText(""+hm );
                txtTM.setText(""+ tm);
                txtPer.setText(""+ per);
                txtGrade.setText(""+ gr);
                txtPS.setText(""+ pf);
                txtAS.setText(""+ as);





            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

}//GEN-LAST:event_CMMouseClicked

    private void CMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMActionPerformed

    private void txtPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerActionPerformed

    private void txtsstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsstActionPerformed

    private void txtTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTMActionPerformed

    private void txtClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassActionPerformed

    private void txtSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Part_Stud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAS;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtMM;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPS;
    private javax.swing.JTextField txtPer;
    private javax.swing.JTextField txtRno;
    private javax.swing.JTextField txtSec;
    private javax.swing.JTextField txtTM;
    private javax.swing.JTextField txteng;
    private javax.swing.JTextField txthin;
    private javax.swing.JTextField txtsc;
    private javax.swing.JTextField txtsst;
    // End of variables declaration//GEN-END:variables

}
